/*
This file is generated by signature.cjs. Do not edit it directly.
./components/DocInterface.js: function DocInterface(doc)
./components/ImmutableInterface.js: function ImmutableInterface(immutable)
./components/Player.js: function Player()
./components/TestContext.js: function TestContext(testName, f)
./functions/bindFunctions.js: function bindFunctions(state, importedFunctions)
./functions/checkCollisionDivs.js: function checkCollisionDivs(div1, div2, )
./functions/checkCollisionRects.js: function checkCollisionRects(rect1, rect2)
./functions/docReady.js: function docReady(fn, )
./functions/drawDivs.js: function drawDivs()
./functions/enumerateFunctions.js: function enumerateFunctions(global)
./functions/enumerateTestFunctions.js: function enumerateTestFunctions(global)
./functions/fitParentToChildren.js: function fitParentToChildren(parent)
./functions/generateGuid.js: function generateGuid()
./functions/getCallingFunctionName.js: function getCallingFunctionName(generateGuid, index)
./functions/getComponentSystemFunctionNames.js: function getComponentSystemFunctionNames()
./functions/getTestFunctionName.js: function getTestFunctionName()
./functions/isComponentSystemFunctionName.js: function isComponentSystemFunctionName(name)
./functions/mergeComponents.js: function mergeComponents(target, state)
./functions/newComponentDecorator.js: function newComponentDecorator(componentFunction, )
./functions/reportAssertion.js: function reportAssertion(name, id, message, success, )
./functions/reportTest.js: function reportTest(name, )
./functions/runTests.js: function runTests(tests, state, testContextInit)
./functions/startComponents.js: function startComponents(importedComponents)
./functions/stopComponents.js: function stopComponents(importedComponents)
./tests/testCollisionDivs.js: function testCollisionDivs(f)
./tests/testCollisionRects.js: function testCollisionRects()
*/

import { DocInterface } from './components/DocInterface.js';
import { ImmutableInterface } from './components/ImmutableInterface.js';
import { Player } from './components/Player.js';
import { TestContext } from './components/TestContext.js';
import { bindFunctions } from './functions/bindFunctions.js';
import { checkCollisionDivs } from './functions/checkCollisionDivs.js';
import { checkCollisionRects } from './functions/checkCollisionRects.js';
import { docReady } from './functions/docReady.js';
import { drawDivs } from './functions/drawDivs.js';
import { enumerateFunctions } from './functions/enumerateFunctions.js';
import { enumerateTestFunctions } from './functions/enumerateTestFunctions.js';
import { fitParentToChildren } from './functions/fitParentToChildren.js';
import { generateGuid } from './functions/generateGuid.js';
import { getCallingFunctionName } from './functions/getCallingFunctionName.js';
import { getComponentSystemFunctionNames } from './functions/getComponentSystemFunctionNames.js';
import { getTestFunctionName } from './functions/getTestFunctionName.js';
import { isComponentSystemFunctionName } from './functions/isComponentSystemFunctionName.js';
import { mergeComponents } from './functions/mergeComponents.js';
import { newComponentDecorator } from './functions/newComponentDecorator.js';
import { reportAssertion } from './functions/reportAssertion.js';
import { reportTest } from './functions/reportTest.js';
import { runTests } from './functions/runTests.js';
import { startComponents } from './functions/startComponents.js';
import { stopComponents } from './functions/stopComponents.js';
import { testCollisionDivs } from './tests/testCollisionDivs.js';
import { testCollisionRects } from './tests/testCollisionRects.js';

const reqs = { getComponentSystemFunctionNames };
const DocInterfaceComponent = newComponentDecorator(DocInterface, reqs);
const ImmutableInterfaceComponent = newComponentDecorator(ImmutableInterface, reqs);
const PlayerComponent = newComponentDecorator(Player, reqs);
const TestContextComponent = newComponentDecorator(TestContext, reqs);

export {
bindFunctions,
checkCollisionDivs,
checkCollisionRects,
DocInterfaceComponent as DocInterface,
docReady,
drawDivs,
enumerateFunctions,
enumerateTestFunctions,
fitParentToChildren,
generateGuid,
getCallingFunctionName,
getComponentSystemFunctionNames,
getTestFunctionName,
ImmutableInterfaceComponent as ImmutableInterface,
isComponentSystemFunctionName,
mergeComponents,
newComponentDecorator,
PlayerComponent as Player,
reportAssertion,
reportTest,
runTests,
startComponents,
stopComponents,
testCollisionDivs,
testCollisionRects,
TestContextComponent as TestContext
};