/*
This file is generated by signature.cjs. Do not edit it directly.
./components/docInterface.js: function docInterface(doc)
./components/player.js: function player()
./functions/bindFunctions.js: function bindFunctions(state, importedFunctions)
./functions/checkCollisionRects.js: function checkCollisionRects(rect1, rect2)
./functions/enumerateFunctions.js: function enumerateFunctions(global)
./functions/enumerateTestFunctions.js: function enumerateTestFunctions(global)
./functions/generateGuid.js: function generateGuid()
./functions/runTests.js: function runTests(tests, state)
./functions/startComponents.js: function startComponents(importedComponents)
./functions/stopComponents.js: function stopComponents(importedComponents)
./stateFunctions/checkCollisionDivs.js: function checkCollisionDivs(functions, div1, div2)
./stateFunctions/checkCollisionDivs.js: function testCollision(state)
./stateFunctions/docReady.js: function docReady(state, fn)
./stateFunctions/drawDivs.js: function drawDivs()
./stateFunctions/getCallingFunctionName.js: function getCallingFunctionName(functions, index)
./stateFunctions/reportAssertion.js: function reportAssertion(functions, name, message, success)
./stateFunctions/reportTest.js: function reportTest(functions, initialization, assertions)
*/

import { bindFunctions } from './functions/bindFunctions.js';
import { checkCollisionDivs } from './stateFunctions/checkCollisionDivs.js';
import { checkCollisionRects } from './functions/checkCollisionRects.js';
import { docInterface } from './components/docInterface.js';
import { docReady } from './stateFunctions/docReady.js';
import { drawDivs } from './stateFunctions/drawDivs.js';
import { enumerateFunctions } from './functions/enumerateFunctions.js';
import { enumerateTestFunctions } from './functions/enumerateTestFunctions.js';
import { generateGuid } from './functions/generateGuid.js';
import { getCallingFunctionName } from './stateFunctions/getCallingFunctionName.js';
import { player } from './components/player.js';
import { reportAssertion } from './stateFunctions/reportAssertion.js';
import { reportTest } from './stateFunctions/reportTest.js';
import { runTests } from './functions/runTests.js';
import { startComponents } from './functions/startComponents.js';
import { stopComponents } from './functions/stopComponents.js';
import { testCollision } from './stateFunctions/checkCollisionDivs.js';

checkCollisionDivs.stateful = true;
docReady.stateful = true;
drawDivs.stateful = true;
getCallingFunctionName.stateful = true;
reportAssertion.stateful = true;
reportTest.stateful = true;
testCollision.stateful = true;

export {
bindFunctions,
checkCollisionDivs,
checkCollisionRects,
docInterface,
docReady,
drawDivs,
enumerateFunctions,
enumerateTestFunctions,
generateGuid,
getCallingFunctionName,
player,
reportAssertion,
reportTest,
runTests,
startComponents,
stopComponents,
testCollision
};