// This file is auto-generated by scripts/signature.cjs. Do not edit.

// import './style.css';

import { checkCollisionDivs } from './functions/checkCollisionDivs.js';
import { checkCollisionRects } from './functions/checkCollisionRects.js';
import { docReady } from './functions/docReady.js';
import { drawDivs } from './functions/drawDivs.js';
import { enumerateFunctions } from './functions/enumerateFunctions.js';
import { enumerateTestFunctions } from './functions/enumerateTestFunctions.js';
import { player } from './components/player.js';
import { report } from './functions/report.js';
import { runTests } from './functions/runTests.js';
import { testCollision } from './functions/checkCollisionDivs.js';

function game() {
    console.log("Game started");
    const currentScript = document.getElementById('index');
    const functions = enumerateFunctions(window);
    // Log all functions
    console.log("Current script", document.currentScript);
    for (const func of functions) {
        console.log(func.name);
    }
};

function main(state) {
    const urlParams = new URLSearchParams(window.location.hash.substring(1));
    if (urlParams.has('test')) {
        runTests();
    } else {
        game();
    }
}

const state = {};
docReady(() => main(state));